### ISSUE TITLE
missing example for login with userpass

### ISSUE THREAD

**Issue by portno12** [jmgilman/vaultrs#28]
the docs only include how to login with a token but `userpass` is listed as supported. can an example of authing with `userpass` please be added?

**Comment by jmgilman** [comment]
You'll likely want to use `vaultrs-login` for that. See the README [here](https://github.com/jmgilman/vaultrs/tree/master/vaultrs-login). It's a sub-package of the main repo that adds some helper methods for handling logins.

**Comment by portno12** [comment]
this helps. thanks.
