### ISSUE TITLE
Panic when building `VaultClientSettings` without an address

### ISSUE THREAD

**Issue by r-arias** [jmgilman/vaultrs#29]
Hi!

I found an issue with the builder for [`VaultClientSettings`](https://docs.rs/vaultrs/latest/vaultrs/client/struct.VaultClientSettings.html).

The following code panics:

```rust
fn main() {
    // VAULT_TOKEN and VAULT_ADDR are both set in the environment

    println!("Building without specifying a token...");
    let settings = VaultClientSettingsBuilder::default()
        .address("https://127.0.0.1:8200")
        .build()
        .unwrap(); // works

    println!("{settings:?}");

    println!("Building without specifying an addr...");
    let settings = VaultClientSettingsBuilder::default()
        .token("TOKEN")
        .build() // panics!
        .unwrap();

    println!("{settings:?}");
}
```

The panic comes from `VaultClientSettingsBuilder::validate` which `unwrap()`s `self.address.as_ref()`.

The problem is that according to [`derive_builder`'s documentation](https://docs.rs/derive_builder/latest/derive_builder/#pre-build-validation)
> Default values are applied after validation, and will therefore not be validated!

So, `validate()` is called before `default_addr()` sets anything, making the unwrap panic.

I have created an [issue](https://github.com/colin-kiegel/rust-derive-builder/issues/251) with `derive_builder`, because I think validation should happen after applying defaults. However, I think the panic here is still avoidable.

See this PR: #30

**Comment by r-arias** [comment]
As you can see in https://github.com/colin-kiegel/rust-derive-builder/issues/251, `derive_builder` has its reasons not to verify on default fields.

> Validation takes place before defaulting for a couple reasons:
> 
> 1. Populating defaults takes work - we may have to create a whole instance of the deriving type, for example. We wanted validation to be "zero-cost" in terms of performance, so that creation would have been tough to accept.
> 
> 2. Defaulting does not write its values into the builder struct fields, so there's no good way to expose those defaulted values to the validation function. Indeed, defaulting and target struct construction are intertwined, so there's no moment where one could observe defaulted values before the target is constructed.

I think that makes sense.

There is also a suggestion on what to do in `vaultrs`:

> Personally, I'd suggest that `vaultrs` use a tighter type for `address`, so that there's not a need to do validation on it at build time. If there's no good existing type, a custom type with `TryFrom<&str>` and `FromStr` impls would work well. In that situation, the default would also need to be changed to `default = "self.default_address()?"` to reflect the possibility of unsuitable data coming in from the environment variable.

**Comment by jmgilman** [comment]
This is an interesting issue, thanks for taking the time to investigate it so thoroughly. I had come across this validate function a while back and had the urge to just remove it as it's really just a nicety for end-users (i.e. an invalid address would eventually show up in a propagated error down the stack). This really came out of a TDD mindset of not allowing improper formats. 

At this point, removing `validate` would likely be too backward-incompatible, so I'm fine with accepting a workaround.

**Comment by r-arias** [comment]
No problem, I just came across it when writing something with a colleague.

So, do you think it's worth replacing `address: String` with `address: Url` in the settings struct? Or should I just keep the PR as-is?

**Comment by jmgilman** [comment]
Yeah, moving to a `URL` seems to be a better approach.

**Comment by r-arias** [comment]
Thanks for the answer. Haven't had time to try it out, but I'll try and put that into #30 .

**Comment by r-arias** [comment]
Hm. If we make `VaultClientSettings::address` a `Url`, then I think I must either make the setter return a `Result` or make it panic when passed a `String` or `&str` that cannot be parsed to a `Url` correctly, right?

```rust
pub struct VaultClientSettings {
    #[builder(setter(custom), default = "self.default_address()?")]
    pub address: Url,
    // ...
}

impl VaultClientSettingsBuilder {
    pub fn address<T>(&mut self, address: T) -> Result<&mut Self, String>
    where
        T: AsRef<str>,
    {
        let url = Url::parse(address.as_ref())
            .map_err(|_| format!("Invalid URL format: {}", address.as_ref()))?;
        self.address = Some(url);
        Ok(self)
    }
    
    // ...
```
or 

```rust
// ...
impl VaultClientSettingsBuilder {
    pub fn address<T>(&mut self, address: T) -> &mut Self
    where
        T: AsRef<str>,
    {
        let url = Url::parse(address.as_ref())
            .expect(&format!("Invalid URL format: {}", address.as_ref()));
        self.address = Some(url);
        self
    }
    // ...
```
Both would be a breaking change, one in the visible API, the other "just" the panic.

I think, making it panic might be the better option for library consumers, because they likely won't have to rewrite their code. And if their vault addresses don't parse right, they're probably running into a panic somewhere later, anyway. What do you think?

**Comment by jmgilman** [comment]
I agree with the second option being better - it would be weird for the panic to be a breaking change to consumers (how was their code working with broken URLs before?). Thanks for the fix :)

**Comment by r-arias** [comment]
well sure, I mean it's a breaking change more in an academic sense :joy:

I'll continue the discussion in the PR, I think it makes more sense there.
