### ISSUE TITLE
Support for cas option in `SetSecretRequest`?

### ISSUE THREAD

**Issue by bodymindarts** [jmgilman/vaultrs#33]
I need to use the compare-and-swap feature of vault and see that it is not currently supported.

I think it would be fairly simple to add [here](https://github.com/jmgilman/vaultrs/blob/master/src/api/kv2/requests.rs#L87-L93) via something like:
```
#[derive(Builder, Debug, Endpoint)]
#[endpoint(
    path = "{self.mount}/data/{self.path}",
    response = "SecretVersionMetadata",
    method = "POST",
    builder = "true"
)]
#[builder(setter(into))]
pub struct SetSecretRequest {
    #[endpoint(skip)]
    pub mount: String,
    #[endpoint(skip)]
    pub path: String,
    pub data: Value,
    pub options: Option<SetSecretRequestOptions>,
}

#[derive(Builder, Clone, Debug, serde::Serialize)]
#[builder(setter(into))]
pub struct SetSecretRequestOptions {
    pub cas: u32,
}
```

is this a feature that would be accepted if I open a PR?

**Comment by jmgilman** [comment]
Hi,

Yes, the proposed solution looks good.

**Comment by bodymindarts** [comment]
PR https://github.com/jmgilman/vaultrs/pull/34 opened. Feedback welcome!

**Comment by bodymindarts** [comment]
Alternative PR that is backwards compatible by adding the `kv2::set_with_options` function:
https://github.com/jmgilman/vaultrs/pull/35
