### ISSUE TITLE
New crate version with last modifications

### ISSUE THREAD

**Issue by chrpron** [jmgilman/vaultrs#52]
Bonjour,

Is it possible to publish a new version of vaultrs on crates.io with the lasts modifications merged on the master branch ?
(notably for namespaces support)

Thanks a lot !

**Comment by ereOn** [comment]
Adding to this: it seems namespace support was added last year but the latest release do not yet contain this feature.

Is there anything we can do to help?

**Comment by jmgilman** [comment]
Sorry for the delay, I started a new job and am now getting around to updating things. Release `v0.7.0` (released today) contains these changes.
