### ISSUE TITLE
ResponseParseError in vaultrs::auth::oidc::role::set

### ISSUE THREAD

**Issue by chaostheory88** [jmgilman/vaultrs#57]
Hi, I've a simple function which tries to enable OIDC authentication.

```rust
/// Enables Google OIDC
    pub async fn enable_google_oidc(
        &self,
        client_id: &str,
        client_secret: &str,
        redirect_url: &str,
    ) -> Result<(), Box<dyn Error>> {
        let mut oidc_config =
            vaultrs::api::auth::oidc::requests::SetConfigurationRequestBuilder::default();

        oidc_config
            .oidc_discovery_url("https://accounts.google.com")
            .oidc_client_id(client_id)
            .oidc_client_secret(client_secret)
            .default_role("authrole");

        vaultrs::auth::oidc::config::set(&self.client, "google_oidc", Some(&mut oidc_config))
            .await?;

        let token_policies = ["reader".to_string()];
        let scopes = [
            "profile".to_string(),
            "email".to_string(),
            "openid".to_string(),
        ];
        let bound_audiences = [client_id.to_string()];
        let allowed_redir_urls = [redirect_url.to_string()];
        let claim_mappings = HashMap::from([
            ("given_name".to_string(), "given_name".to_string()),
            ("family_name".to_string(), "family_name".to_string()),
            ("email".to_string(), "email".to_string()),
            ("sub".to_string(), "sub".to_string()),
            ("name".to_string(), "name".to_string()),
        ]);

        let mut oidc_auth_role =
            vaultrs::api::auth::oidc::requests::SetRoleRequestBuilder::default();
        oidc_auth_role
            .token_policies(token_policies)
            .oidc_scopes(scopes)
            .bound_audiences(bound_audiences)
            .role_type("oidc")
            .claim_mappings(claim_mappings);

        vaultrs::auth::oidc::role::set(
            &self.client,
            "google_oidc",
            "authrole",
            "email",
            allowed_redir_urls.to_vec(),
            Some(&mut oidc_auth_role),
        )
        .await?;

        Ok(())
    }
```
However the `vaultrs::auth::oidc::role::set` function returns the following error after executing it despite the call seems to execute correctly:

```sh
RestClientError {
    source: ResponseParseError {
        source: Error("EOF while parsing a value", line: 1, column: 0),
        content: Some(
            "",
        ),
    },
}
```

Here there's the request/response payload captured using Wireshark:

```sh
POST /v1/auth/google_oidc/role/authrole HTTP/1.1
x-vault-token: hvs.E1g3PCrdjvPVslGEMTRoIqwz
accept: */*
host: localhost:8200
content-length: 321

{"allowed_redirect_uris":["http://localhost:8200"],"user_claim":"email","bound_audiences":["google_oidc_client_id"],"claim_mappings":{"given_name":"given_name","name":"name","email":"email","family_name":"family_name","sub":"sub"},"oidc_scopes":["profile","email","openid"],"role_type":"oidc","token_policies":["reader"]}

HTTP/1.1 204 No Content
Cache-Control: no-store
Content-Type: application/json
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Thu, 27 Apr 2023 08:59:57 GMT
```

Vault version used: Vault v1.13.1 (4472e4a3fbcc984b7e3dc48f5a8283f3efe6f282), built 2023-03-23T12:51:35Z

Am I doing something wrong?

Kind Regards.

**Comment by Haennetz** [comment]
Hey sorry for the delayed responses.
Can you provide a stack trace? You can enable that feature by setting the env variable `RUST_BACKTRACE` to `1`.
I tried to reproduce it unfortunately I don't have a Google account, so I used a different OIDC Provider to test it.

**Comment by stormshield-gt** [comment]
> Error("EOF while parsing a value", line: 1, column: 0),

This error means that's the HTTP response had an empty body and we were expecting one. This can happen for methods that can both create and update, like [the one you have used](https://developer.hashicorp.com/vault/api-docs/auth/jwt#create-update-role). 
The empty body case can happen when you are in updating mode but the parameters you provided don't have new information, so there is no real update.

In that case we are already ignoring the result (`vaultrs::auth::oidc::role::set` returns unit `()`) changing the implementation of the function from `api::exec_with_empty_result` to `api::exec_with_empty` should do the work.

This does raise a bigger concern about how we should handle this create/update function in the library. I've come up with 4 solutions: 

1) catch the error in the calling function and return a clearer error (like i did in https://github.com/jmgilman/vaultrs/pull/77)  
<details>
<summary> Here a sample of the code </summary>

```rust
 api::exec_with_result(client, endpoint)
            .await
            .map_err(|err| {
                // In the case the response as an empty HTTP Body
                if matches!(
                    err,
                    ClientError::RestClientError {
                        source: rustify::errors::ClientError::ResponseParseError { .. }
                    }
                ) {
                    return ClientError::InvalidUpdateParameter;
                }
                err
            })
```

</details>

2) systematically return `api::exec_with_empty` in that case. But sometimes the information returned is useful, so the user would have to issue both a create and then a read. This gets worse when the create method returns an id, where sometimes we have to do a list (to get the id) and then a read.
3) have an hybrid method `execute_with_result_or_empty`. I've also experimented this workaround in https://github.com/jmgilman/vaultrs/pull/77 , but I remove it at the end. Indeed, it adds an option to the return type, so we are complexifying the most common use cases, for something that shouldn't exist (update with wrong parameters)
<details>

<summary>Here was my working implementation</summary>

```rust
/// Executes an [Endpoint] and if it returns an empty HTTP response, it returns `None`, otherwise it returns the result.
///
/// This function is mostly useful for endpoints that can both *update* and *create*.
/// The *create* operation will return a result and the *update* one not.
///
/// If there is a result, a few operations are performed on it:
///
/// * Any potential API error responses from the execution are searched for and,
///   if found, converted to a [ClientError::APIError]
/// * All other errors are mapped from [rustify::errors::ClientError] to
///   [ClientError::RestClientError]
/// * An empty content body from the execution is rejected and a
///   [ClientError::ResponseEmptyError] is returned instead
/// * The enclosing [EndpointResult] is stripped off and any warnings found in
///   the result are logged
/// * An empty `data` field in the [EndpointResult] is rejected and a
///   [ClientError::ResponseDataEmptyError] is returned instead
/// * The value from the enclosed `data` field is returned along with any
///   propagated errors.
pub async fn exec_with_result_or_empty<E>(
    client: &impl Client,
    endpoint: E,
) -> Result<Option<E::Response>, ClientError>
where
    E: Endpoint,
{
    info!(
        "Executing {} and expecting maybe a response",
        endpoint.path()
    );
    endpoint
        .with_middleware(client.middle())
        .exec(client.http())
        .await
        .map(|res| {
            if res.response.body().is_empty() {
                Ok(None)
            } else {
                res.wrap::<EndpointResult<_>>()
                    .map_err(ClientError::from)
                    .map(strip)?
                    .map(Some)
                    .ok_or(ClientError::ResponseDataEmptyError)
            }
        })
        .map_err(parse_err)?
}
``` 

</details>

4) Separate the create and the update functionality in 2 functions, even if they talk to the same endpoint. The create one will always return data ( `api::exec_with_result`) and we are could simply ignore the return of the update which is less useful in that case (`api::exec_with_empty`). The disadvantage is we are not one one with the API but I think it's the more idiomatic

In all cases, we should definitely look how the [go implementation](https://github.com/hashicorp/vault-client-go?tab=readme-ov-file#authentication) (or other SDK)  is dealing with such cases

**Comment by Haennetz** [comment]
@stormshield-gt thanks for the suggestions and the explanation of the error.
1. I don't like this one because it blots the calling functions.
2. I also don't like this option, because the reason you already mention.
3. If we add a new `exec_with_result_or_empty` fiction to the API it can be hard to determine when to use `exec_with_result` and `exec_with_result_or_empty`. In the vault documentation they don't mention if they return an empty response or not. We should check if we can solve this in the current `api::exec_with_result`
4. also cause a lot of bloated code.

I will look into the option 3.
